curiosProject/curiosProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login_signup.urls')),
    path('ques/', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

curiosProject/posts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', post_list, name='list'),
    path('create/', post_create, name='create'),
    path('<int:id>/', post_detail, name='detail'),
    path('<int:id>/edit/', post_update, name='update'),
    path('<int:id>/delete/', post_delete)
]
app_name = 'posts'

curiosProject/posts/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone


# Create your models here.

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    # filebase, extension = filename.split('.')
    # return "%s/%s.%s" %(instance.id,filename.id,extension)
    return "%s/%s" % (instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field='width_field',
                              height_field='height_field')
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    objects = PostManager()  # if I save it as post=PostMannager() then it would be called as : Post.post.all()

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"id": self.id})

    class Meta:
        ordering = ['-timestamp', '-updated']

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, instance.id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_reciever, sender=Post)

curiosProject/posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
    publish = forms.DateField(widget=forms.SelectDateWidget)
    content = forms.CharField(widget=PagedownWidget)
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

curiosProject/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from urllib.parse import quote_plus
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from comments.models import Comment
from comments.forms import CommentForm
from django.db.models import Q
from django.contrib.auth.models import User
from .forms import PostForm
from .models import Post
# Create your views here.


def post_create(request):
    if not request.user.is_authenticated:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user.username
        instance.save()
        messages.success(request, 'Successfully Created')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form
    }
    return render(request, "post_form.html", context)


def post_detail(request, id=None):
    #instance = Post.objects.get(id=2)
    instance = get_object_or_404(Post, id=id)
    if instance.draft or instance.publish>timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)
    initial_data = {
        'content_type': instance.get_content_type,
        'object_id':instance.id
    }
    print(instance.get_content_type)
    #####To Addd comments functionality here!!!!
    comments = Comment.objects.filter_by_instance(instance)
    comment_form = CommentForm(request.POST or None,initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated:
        content_data = comment_form.cleaned_data.get('content')
        new_comment, created = Comment.objects.get_or_create(user=request.user,content_type=instance.get_content_type,object_id=instance.id,content=content_data)
        if created:
            print('Yaye! created...')
    comp_url = 'http://127.0.0.1:8000' + request.get_full_path()
    context = {
        'post_detail': instance,
        'share_string': share_string,
        'comp_url': comp_url,
        'comments': comments,
        'comment_form':comment_form,
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    today = timezone.now().date()
    queryset = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
            ).distinct()
    context = {
        'obj_list': queryset,
        'today':today,
    }
    return render(request, "post_list.html", context)


def post_update(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None,
                    request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Successfully Created')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title': instance.title,
        'instance': instance,
        'form': form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, 'Successfully Deleted')
    return redirect('posts:list')

curiosProject/templates/about.html
{% extends 'base.html' %}
{% block title %}ABOUT US{% endblock %}
{% block content %}

<div class="container-fluid mt-3" style="background-color: #4938a2;">
    <div class="row p-4">
        <div class="col-md-6 align-center">
            <h4 class="text-white">Hardik Pachory</h4>
            <p class="text-white">Hello, this is Hardik Pachory. I am a CSE student, an artist and a software engineer to be.
                I started with C++ and tried working with Python and JavaScript as well. I have knowledge of MERN web app,
                and building Django skills. Learning and implementing is my hobby, and I my special ability is that I can ADAPT.
            </p>
            <div class="row">
                <div class="col-sm-1">
                    <a href="https://github.com/hardik-pachory" target="_blank"><i class="fab fa-github" style="color:#fff;"></i></a>
                </div>
                <div class="col-sm-1">
                    <a href="https://www.instagram.com/the_hardik_pachory/?hl=en" target="_blank"><i class="fab fa-instagram" style="color:#fff;"></i></a>
                </div>
                <div class="col-sm-1">
                    <a href="https://www.facebook.com/hardik.pachory.5/" target="_blank"><i class="fab fa-facebook" style="color:#fff;"></i></a>
                </div>
                <div class="col-sm-1">
                    <a href="https://www.linkedin.com/in/hardikpachory/" target="_blank"><i class="fab fa-linkedin" style="color:#fff;"></i></a>
                </div>
            </div>
        </div>
        <div class="col-md-6 mt-4">
            <blockquote class="blockquote text-center bg-white p-5">
                <p class="mb-0">Learn continually - there's always </p>
                <span class="mb-0 text-info">"ONE MORE THING"</span>
                <p>to learn.</p>
                <footer class="blockquote-footer"><cite title="Source Title">- Steve Jobs</cite></footer>
            </blockquote>
        </div>
    </div>
</div>


{% endblock %}

curiosProject/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="icon" type="image/gif/png" href="{% static 'images/curios.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}Curios{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base_style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
  </head>
  <body>
    <!-- Just an image -->
    <section id="menu">
    <div class="nav">
      <a class="navbar-brand" href="{% url 'startpage' %}" style="margin-left:2rem;">
        <img src="{% static 'images/curios.png' %}" width="100" height="60" alt="">
      </a>
        <a class="nav-link p-3" href="/">Home <span class="sr-only">(current)</span></a>
        <a class="nav-link p-3" href="{% url 'about' %}">About Us</a>
        {% if request.user.is_authenticated %}
        <a class="nav-link p-3" href="{% url 'posts:list' %}">Questions</a>
        {% endif %}
        {% if not request.user.is_authenticated %}
        <a class="nav-link p-3" href="{% url 'login' %}" style="margin-left:auto;">Login</a>
        <a class="nav-link p-3" href="{% url 'register' %}">Register</a>
        {% else %}
        <a class="nav-link p-3" href="{% url 'posts:create' %}" style="margin-left:auto;">Ask Question</a>
        <a class="nav-link p-3" href="{% url 'logout' %}" style="">Logout</a>
        {% endif %}
    </div>
    </section>

    {% block content %}
    <section>
      <div class="row">
        <div class="col-md-8 offset-2">
      <blockquote class="blockquote p-3 text-center" style="background-color:beige;border-radius:1%;margin-top:3rem;">
        <p class="mb-0 text-dark">Knowledge of what is possible is the beginning of happiness.</p>
        <footer class="blockquote-footer"><cite title="Source Title">George Santayana</cite></footer>
      </blockquote>
        </div>
        </div>
      <div class="p-5"></div>
      <div class="container_fluid">
        <div class="row">
          <div class="col-md-7">
            <h1 class="text-center">A place to calm your curiosity</h1>
            <p style='padding-left: 4%;padding-top:3%;'>This Web Application allows user to ask questions and give
            answers to problems asked by other users. The main motto of this application
            is to spread togetherness and encourage helpful behaviour. Where every person is busy
            in building there own career and fulfilling their future goals, it is quite possible
            to fall in a problem that is hard to solve at single level. Our platform is like a remedy
            for those to provide them with a helping hand to drag them out of their problem. Users
            will work to solve others' doubts and clear theirs as well. Together we rise!</p>
          </div>
          <div class="col-md-5">
            <img style="box-shadow: 1px 1px 30px #99eaea;" class="rounded mx-auto d-block" src="{% static 'images/brain_image.jpg' %}" width="80%">
          </div>
        </div>
        <div class="p-5"></div>
        <div class="row">
          <div class="col-md-5">
            <img style="box-shadow: 1px 1px 30px green;" class="rounded mx-auto d-block" src="{% static 'images/ques.jpg' %}" width="80%">
          </div>
          <div class="col-md-7">
            <h1 class="text-center">What can you do?</h1>
            <p style='padding-left: 4%;padding-top:3%;'>Your knowledge and wisdom can help a beginner
            with his/her journey wonderful and fun. When answering to a particular problem you can also have a look
            at other person's approach and their complexity, this will make your abilities of problem solving more optimised
            and a skill to skim up and understand other person's approach. When you help someone with knowledge you
            also help yourself with that knowledge. Your command over that topic increases and concepts get more clear.</p>
          </div>
        </div>
        <div class="p-5"></div>
      </div>
    </section>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

curiosProject/templates/login.html
{% extends 'base.html' %}
{% block title %}Curios | Login{% endblock%}
{% block content %}
<div class="row">
    <div class="mt-1 pt-2 col-md-8 offset-2 text-white" style="background-color:#597b9c;border-radius:1rem;">
        <h4 class="text-center">Login</h4>
    </div>
</div>
<div class="col-md-10 offset-1">
    <form method="POST" class="pt-4">
        <div class="form-group col-md-10 offset-1 pt-2">
            {% csrf_token %}
            {% for f in form %}
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="text-left col-md-3">
                        <h6>{{f.label}}</h6>
                    </div>
                    <div class="col-md-5">
                        <p class="justify-content-start" >{{f}}</p>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-4 offset-4">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Login" name="Login">
        </div>
    </form>
</div>
{% endblock %}

curiosProject/templates/post_detail.html
{% extends 'base.html' %}
{% block title %}{{block.super}} | {{post_detail.title}}{% endblock %}
<!--<style>
{% block style %}
h1{
    color:#123456;
}
{% endblock style %}
</style> -->
{% block content %}
    <div class='col-md-6 offset-3'>
        {% if post_detail.image %}
        <img src='{{post_detail.image.url}}' class='pt-4 img-fluid'/>
        {% endif %}
        <h1 class="text-center">{{post_detail.title}}</h1>
        <small class='pl-2'>
            <span style="" id="edit">
                <a id="edits" style="text-decotation:none;color:red;" href="edit">Edit</a>
            </span>
            {% if post_detail.draft %}
                <span class='pr-4' style='color:red;'>Draft</span>
            {% endif %}

            <span  style="margin-left:70%;color:#75b6f0;">{{post_detail.publish}}</span>
        </small>
        <p class="p-1"></p>

        {% if post_detail.user.username %}
        <p>Curio : {{post_detail.user.username}}</p>
        {% endif %}


        <div>
        {{post_detail.content}}
        </div>
        <a class="pt-2 offset-9 pb-2 btn btn-danger" href="delete">Delete Question</a>
        <br>
        <hr style="border-top:1px solid #81c784;">
        {% if request.user.is_authenticated %}
        <h3>Comments</h3>
        <form method='POST' class="form-group" action=''>
            <div class="row">
            {% csrf_token %}
                <div class="col-md-6 form-control">
                    {% for f in comment_form %}
                        {{ f }}
                    {% endfor %}
                </div>
            <!--{{comment_form}} -->
                <div class="col-md-6">
                    <input type='submit' value='Add Comment' class='btn btn-primary'>
                </div>
            </div>
        </form>
        {% endif %}
        <p class='p-2'></p>
        {% for comment in comments %}
        <div class='card'>
            <div class='card-body'>
                <h6 class='card-title text-dark'>{{post_detail.user.username}}<small style='color: #419ba4;margin-left: 16rem;'>{{comment.timestamp|timesince}}</small></h6>
                <p class='card-text' style="color:black;">{{comment.content}}</p>
            </div>
        </div>
        <div class='p-1'></div>
        {% endfor %}
       <!-- <div class="fb-comments" data-href="{{comp_url}}" data-width="" data-numposts="5"></div>
    -->
    </div>
{% endblock%}

curiosProject/templates/post_form.html
{% extends 'base.html' %}
{% block head_extra %}
    <div class='col-md-6 offset-3'>
        {{form.media}}
    </div>
{% endblock head_extra %}
    {% block content %}
    <div class='col-md-6 offset-3'>
        <h1 class='text-center pt-1 pb-3'>Ask your question</h1>
        <form method='POST' action ='' enctype='multipart/form-data'>
        {% csrf_token %}
            {% for f in form%}
            <div class="row p-1">
                <div class="offset-3 col-md-3">
                    {{f.label}}
                </div>
                <div class="col-md-6">
                    {{f}}
                </div>
            </div>
            {% endfor %}
            <div class="offset-6 pt-3">
            <input type='submit' class='btn btn-primary' style="width:12rem;" value='Ask Now' />
            </div>
        </form>
    </div>
    {% endblock content %}

curiosProject/templates/post_list.html
{% extends 'base.html' %}

{% block content %}

    <div class='col-md-6 offset-3'>

        <div class="pt-4"></div>
    <form method='GET' class="form-group" action=''>
        <div class="row">
            <div class="col-md-6 offset-2">
                <input type='text' name='q' class="form-control" placeholder='Search Question' value='{{request.GET.q}}'/>
            </div>
            <div class="col-md-2">
                <input type='submit' class="btn btn-danger" value ='Search' />
            </div>
        </div>
    </form>
    {% for obj in obj_list %}
    <div class='row pt-3'>
        <div class='col-md-12'>
            <div class="card">
                {% if obj.image %}
                    <div style='background: rgb(67,64,69);background: linear-gradient(90deg, rgba(67,64,69,1) 0%, rgba(233,244,231,1) 50%, rgba(67,64,69,1) 100%);'>
                    <img src='{{obj.image.url}}' class='card-img-top img-responsive offset-4' style="width:15rem;">
                    </div>
                {% endif %}
                <div class="card-body">
                    {% if obj.darft %}
                        <h3>Staff Only : DRAFT</h3>
                    {% endif %}
                    {% if obj.publish > today %}
                        <h3>Staff Only : Future Post</h3>
                    {% endif %}
                    <h5 class="card-title"><a href='{% url "posts:detail" id=obj.id %}'>{{obj.title}}</a>
                    <small>{{obj.publish}}</small>
                    </h5>
                    <p class="card-text">
                        {% if obj.user.username %}
                        <p class="text-dark">
                            Author : {{obj.user.username}}
                        </p>
                        {% endif %}
                        <span class='content-markdown text-dark'>
                        {{obj.content|truncatechars:60}}
                        </span>
                    </p>
                    <a href="{% url 'posts:detail' id=obj.id %}" class="btn btn-primary">View</a>
                </div>
            </div>
        </div>
    <hr/>
    </div>
    {% endfor %}

    </div>

{% endblock  %}

<!--<a href='{% url "posts:detail" id=obj.id %}'>{{obj.title}}</a><br>
        {{obj.content|linebreaks|truncatechars:30}}<br>
        {{obj.timestamp}}<br>
        {{obj.updated}}<br>
        {{obj.id}}<br>
        <br>-->

curiosProject/templates/register.html
{% extends 'base.html' %}
{% block title %}Curios | {{title}}{% endblock %}
{% block content %}
<div class="row">
    <div class="mt-1 pt-2 col-md-8 offset-2 text-white" style="background-color:#597b9c;border-radius:1rem;">
        <h4 class="text-center">{{title}}</h4>
    </div>
</div>
<div class="col-md-10 offset-1">
    <form method="POST" class="pt-4">
        <div class="form-group col-md-10 offset-1 pt-2">
            {% csrf_token %}
            {% for f in form %}
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="text-left col-md-3">
                        <h6>{{f.label}}</h6>
                    </div>
                    <div class="col-md-5">
                        <p class="justify-content-start" >{{f}}</p>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            {% endfor %}
        </div>
        <div class="col-md-4 offset-4">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Register" name="Register">
        </div>
    </form>
</div>
{% endblock %}